### ISSUE TITLE
Usage in Angular JS app

### ISSUE THREAD

**Issue by vavrecka** [kenkeiter/skeuocard#132]
Hey guys,
I have troubles setting up the form in my Angular JS app.
I have posted question on stackoverflow as well: http://stackoverflow.com/questions/22444480/skeuocard-in-angular-app
I basically copied the working example into my Angular JS app and I am constantly getting this error:

```
TypeError: Cannot read property 'length' of undefined
    at Skeuocard._importImplicitOptions (http://127.0.0.1:9000/lib/skeuocard/javascripts/skeuocard.min.js:1:4226)
    at new Skeuocard (http://127.0.0.1:9000/lib/skeuocard/javascripts/skeuocard.min.js:1:1162)
    at new controller (http://127.0.0.1:9000/js/modules/OtherDirectives.js:98:32)
    at invoke (http://127.0.0.1:9000/lib/angular/angular.js:3760:17)
    at Object.instantiate (http://127.0.0.1:9000/lib/angular/angular.js:3771:23)
    at http://127.0.0.1:9000/lib/angular/angular.js:6881:28
    at http://127.0.0.1:9000/lib/angular/angular.js:6268:34
    at forEach (http://127.0.0.1:9000/lib/angular/angular.js:329:20)
    at nodeLinkFn (http://127.0.0.1:9000/lib/angular/angular.js:6255:11)
    at http://127.0.0.1:9000/lib/angular/angular.js:6529:13 
```

No idea why, I have tried passing default values, names of the inputs, dumping jQuery init, no luck. Do you support angular usage?

Thanks a bunch!

**Comment by PavelTyk** [comment]
@vavrecka how did you get the angular data-binding to work?
